# general settings
simulation:
  random_seed: 42
  observe_time: 20
  output_dir: "./results"

# sampling parameters
sampling_parameters:
  num_sampling_simulations: 100
  grid:
    split_threshold: 0.5
    num_divisions_lower: 50
    num_divisions_upper: 50

# epidemiological parameters
epi_parameters:
  local_growth_rate: 0.25
  importation_rate:
    type: "constant"
    value: 100
    # type: "exponential"
    # params:
    #   M0: 200
    #   rate: -0.3