input_file: "./results/T10.csv.gz"
output_dir: "./results"
num_draws: 200
random_seed: 42

# for calculating lineage detection probabilities
sampling_grid:
  split_threshold: 0.05
  num_divisions_lower: 30
  num_divisions_upper: 30

# for calculating inferred importation intensities
temporal_analysis:
  enabled: true
  # only calculate for these specific sampling proportions
  target_proportions: [0.01, 0.05, 0.15, 0.5, 0.9]