simulation:
  seed: 42
  num_agents: 100000
  num_steps: 20
  num_experiments: 20
  num_patient_zero: 0 # number of initial infected agents (at home location) (default: 0)
  output_dir: "./results"

# Define the dynamic parameters
parameters:
  beta:
    type: "constant"
    value: 0.025

  kappa:
    type: "sigmoid"
    params:
      a: 10   # time-shift
      b: 1.5  # steepness
      c: 10   # initial value
      d: 1    # final value

  gamma:
    type: "constant"
    value: 0.1

  importation:
    type: "exponential"
    params:
      initial: 1
      growth: 0.2